name: Build and Stop Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ${{ github.workspace }}/tools
        docker compose up -d 

    - name: Compile documents
      run: |
        cd ${{ github.workspace }}/tools
        docker exec argo-docs-latexpdfbuilder-1 bash -c 'cd /data && chmod +x *.sh && ./compilescript.sh -a'

    - name: Commit and push changes
      run: |
        ls
        mv build-output Docs

    - name: Imposta la variabile d'ambiente per il percorso della cartella
      run: echo "export FOLDER_PATH=$(pwd)/Docs" >> $GITHUB_ENV

    - name: Checkout nella nuova repo
      uses: actions/checkout@v4
      with:
        repository: Rikicavaz77/prova_destination
        ref: main  

    - name: Commit e push nella nuova repository
      env:
        FOLDER_PATH: ${{ env.FOLDER_PATH }}
      run: |
        git config --global user.name 'bot'
        git config --global user.email 'riccardo.cavalli@studenti.unipd.it'
        git add .
        git commit -m "Aggiornamento dalla cartella $FOLDER_PATH"
        git push
    
    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Documentazione
        path: |
          build
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
            
    - name: Stop Docker Compose
      run: |
        cd ${{ github.workspace }}/tools
        docker compose stop
